app/urls.py
from django.urls import path

from .views import *

app_name = 'app' 


urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('<int:id>/', SearchView.as_view(), name='home'),
    path('add_user/', AddUser.as_view(), name='add_user'),
    path('del_user/', DelUser.as_view(), name='del_user'),
    path('handler_user/', HandlerUser.as_view(), name='handler_user'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('change_password/', ChangePassword.as_view(), name='change_password'),
    path('sync_db/', SyncDb.as_view()),   
    path('service/', Service.as_view(), name='services'),   
    path('service_handler/', ServiceHandler.as_view()),   
    path('search_user/', SerchUserHandler.as_view()),     
    path('online_users/', OnlineUsers.as_view()),     
]

ocserv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models
from django.utils import timezone

class OcservUser(models.Model):
    oc_username = models.CharField(max_length=16)
    oc_password = models.CharField(max_length=32)
    oc_active = models.BooleanField(default=True)
    create = models.DateTimeField(auto_now_add=True)
    expire_date = models.DateField(null=True, blank=True)
    desc = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.oc_username

    @property
    def expire(self):
        if self.expire_date and self.expire_date <= timezone.now().date():
            return True
        return False

    class Meta:
        verbose_name = "Ocserv User"
        verbose_name_plural = "Ocserv Users"
        ordering = ["-create",]

app/templates/add_user.html
{% extends 'base.html' %}

{% block body %}
<h2 class="mb-4 mt-4">Add User Page</h2>
<div class="row">
    <div class="col-10">
        <div class="d-flex justify-content-center">
            <div class="py-4 px-4 rounded text-left" style="border: 2px solid black;">
                <form method="post">
                    {% csrf_token %}
                    <div class="row d-flex justify-content-center">
                        <div class="col-4">
                            <div class="form-group mb-3">
                                <label class="mb-2" for="oc_username">Oc Username : </label>
                                {{ form.oc_username }}
                            </div>
                            <div class="form-group mb-3">
                                <label class="mb-2" for="oc_password">Oc Password : </label>
                                {{ form.oc_password }}
                            </div>
                            <div class="form-group mb-3">
                                <label class="mb-2" for="expire_date">Expiration Date : </label>
                                {{ form.expire_date }}
                                <small class="text-capitalize text-success">leave blank for the user without an expiration date </small>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group mb-4">
                                <label class="" for="desc">User Description : </label>
                                {{ form.desc }}
                            </div>
                        </div>
                        {% if error or success %}
                        <div class="col-4 mt-5">
                            {% if form.oc_username.errors.0 %}
                            <div class="bg-danger px-3 py-2 rounded text-center my-4" style="font-size: 14px;">
                                {{ form.oc_username.errors.0 }}
                            </div>
                            {% endif %}
                            {% if form.expire_date.errors.0 %}
                            <div class="bg-danger px-3 py-2 rounded text-center my-4" style="font-size: 14px;">
                                {{ form.expire_date.errors.0 }}
                            </div>
                            {% endif %}
                            {% if success %}
                            <br>
                            <div class="bg-success px-3 py-2 rounded text-center my-2 text-capitalize mt-5" style="font-size: 14px;">
                                {{ success }} added successfully
                            </div>
                            {% endif %}
                        </div>
                        {% endif %}
                        <div class="col-12">
                            <div class="text-center">
                                <input type="submit" value="Add User" class="btn btn-outline-success">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-2 py-2 text-center" style="border: 2px solid black;">
        <h4 class="text-center mt-4">Last Users</h4>
        {% for user in last_users %}
        <blockquote>
            {{ user }}
        </blockquote>
        {% endfor %}
    </div>
</div>

<script>
    $('#id_expire_date').datepicker({
        format: "yyyy-mm-dd",
        clearBtn: true,
        templates: {
            leftArrow: '<i class="fa fa-long-arrow-left"></i>',
            rightArrow: '<i class="fa fa-long-arrow-right"></i>'
        },
        todayHighlight: true,
    });
</script>

{% endblock %}

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"
        integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ=="
        crossorigin="anonymous"></script>
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css"
        integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw=="
        crossorigin="anonymous" />
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker-en-CA.min.js"
        integrity="sha512-XyW6VyuUyLXiWM3BtbdTto6mXYFO9P1J3qO2GY1toAld5aLXhkNkLBQXqQoZm8Je86cCdDZn7ZG9ZQPbIWN60g=="
        crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
</head>

<body class="bg-dark text-white">
    {% include 'navbar.html' %}
    <div class="container">
        {% block body %} {% endblock %}
    </div>
</body>

</html>

app/templates/change_password.html
{% extends 'base.html' %}

{% block body %}
<div class="d-flex justify-content-center ">
    <div class="py-4 px-5 mt-5" style="border: 2px solid black;width: 50%;">
        <h2 class="mb-4">Change Password Page</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group mb-5">
                <label class="mb-2" for="old_password">Old Password : </label>
                <input type="password" class="form-control" id="old_password" placeholder="Old Password" name="old_password">
            </div>
            <div class="form-group mb-5">
                <label class="mb-2" for="new_password">New Password : </label>
                <input type="password" class="form-control" id="new password" placeholder="New Password" name="new_password">
            </div>
            <input class="btn btn-lg btn-outline-success mb-3" type="submit" value="Change Password">
        </form>
        {% if error %}
        <center>
        <h6 class="bg-danger px-5 py-2 rounded">
            {{ error }}
        </h6>
        <center>
        {% endif %}
        </form>
    </div>
</div>

{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<style>
    .pagination>li>a {
        background-color: #343a40;
        color: white;
    }

    .pagination>li>a:focus,
    .pagination>li>a:hover,
    .pagination>li>span:focus,
    .pagination>li>span:hover {
        color: black;
        background-color: #343a40;
        border-color: white;
    }

    .pagination>.active>a {
        color: black !important;
        background-color: white !Important;
        border: solid 1px white !Important;
    }

    .pagination>.active>a:hover {
        background-color: white !Important;
        border: solid 1px white;
    }
</style>
</style>
{% endblock %}

{% block body %}
<h2 class="mt-4">User Management Page</h2>

{% if search %}

<div class="py-2" style="border: 2px solid black;">
    <h5 class="mx-3">Online Users</h5>
    <span id="online_users" class="mx-4 text-primary text-justify">
    </span>
</div>

<div class="row mt-4 mb-4">
    <div class="col-4">
        <div class="ui-widget">
            <input id="userSearch" placeholder="Search User" class="form-control">
        </div>
    </div>
    <div class="col-8 text-right">
        <button class="btn btn-outline-success" onclick="syncDb()">
            <i class="fa fa-refresh mx-1" aria-hidden="true"></i>
            Ocpasswd Synchronise
        </button>
    </div>
</div>
{% endif %}
<table class="table table-striped table-dark">
    <thead>
        <tr class="text-center">
            <th scope="col">Create At</th>
            <th scope="col">Ocserv Username</th>
            <th scope="col">Ocserv Password</th>
            <th scope="col">Expire Date</th>
            <th scope="col">Active</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for user in object_list %}
        <tr class="text-center">
            <td scope="row">{{ user.create | date:'Y-m-d' }}</td>
            <td>{{ user.oc_username }}</td>
            <td>{{ user.oc_password }}</td>
            <td>{{ user.expire_date | date:'Y-m-d' }}</td>
            <td>{{ user.oc_active }}</td>
            <td>
                {% if user.oc_active %}
                <button class="btn btn-outline-warning btn-sm mx-1" onclick="userHandler('{{ user.id }}', 'deactive')"
                    id="deactive-{{ user.id }}">
                    Deactive
                </button>
                {% else %}
                <button class="btn btn-outline-info btn-sm  mx-1" onclick="userHandler('{{ user.id }}', 'active')"
                    id="active-{{ user.id }}">
                    Active
                </button>
                {% endif %}
                <button class="btn btn-outline-danger btn-sm" onclick="deleteUser('{{ user.id }}')"
                    id="del-{{ user.id }}">Delete</button>
                <button class="btn btn-outline-danger btn-sm" style="display: none;"
                    onclick="confirmDelete('{{ user.id }}')" id="confirm-{{ user.id }}">Delete</button>
                <button class="btn btn-outline-light btn-sm mx-1" style="display: none;"
                    onclick="cancelDelete('{{ user.id }}')" id="cancel-{{ user.id }}">Cancel</button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% if page_obj.has_next or page_obj.has_previous %}
<nav aria-label="Page navigation bg-dark" class="mt-5 mb-5">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous and page_obj.paginator.num_pages > 5 %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %} <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next and page_obj.paginator.num_pages > 5 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            {% endif %}
    </ul>
</nav>
{% endif %}

{% if not search %}
<div class="text-center mt-3">
    <button onclick="window.location.href='/';" class="btn btn-outline-success btn-lg mx-3">Home</button>
    <button onclick="window.history.back();" class="btn btn-outline-light btn-lg">back</button>
</div>
{% endif %}

<script>
    function deleteUser(userId) {
        $('#del-' + userId).css('display', 'none');
        $('#confirm-' + userId).css('display', 'inline');
        $('#cancel-' + userId).css('display', 'inline');
        $('#deactive-' + userId).css('display', 'none');
        $('#active-' + userId).css('display', 'none');
    }
    function cancelDelete(userId) {
        $('#del-' + userId).css('display', 'inline');
        $('#confirm-' + userId).css('display', 'none');
        $('#cancel-' + userId).css('display', 'none');
        $('#deactive-' + userId).css('display', 'inline');
        $('#active-' + userId).css('display', 'inline');
    }
    function confirmDelete(userId) {
        $.ajax({
            url: "/del_user/",
            data: {
                'user_id': userId,
            },
            success: function (response) {
                location.reload(true);
            },
            error: function (response) {
                alert(response["responseJSON"]["error"]);
            }
        });
    }
    function userHandler(userId, action) {
        $.ajax({
            url: "/handler_user/",
            data: {
                'user_id': userId,
                'action': action,
            },
            success: function (response) {
                location.reload(true);
            },
            error: function (response) {
                alert(response["responseJSON"]["error"]);
            }
        });
    }
    function syncDb() {
        $.ajax({
            url: "sync_db/",
            success: function (response) {
                location.reload(true);
            },
            error: function (response) {
                alert("'chmod 644 /etc/ocserv/ocpasswd' to get access to sync ocpasswd with db")
            }
        });
    }

    function getOnlineUsers() {
        $.ajax({
            url: "online_users/",
            success: function (response) {
                let userSpan = $("#online_users")
                userSpan.html("")
                for (var name of response) {
                    userSpan.append(" #" + name)
                }
            },
        });
    }

    window.setInterval(function () {
        getOnlineUsers()
    }, 120000);

    $(document).ready(() => {
        getOnlineUsers()
    })

    $(function () {
        $("#userSearch").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: "/search_user/",
                    data: {
                        search_param: request.term
                    },
                    success: function (data) {
                        response(data);
                    }
                });
            },
            minLength: 2,
            select: function (event, ui) {
                location.href = '/' + ui.item.id + "/";
            }
        });
    });
</script>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block body %}
<div class="d-flex justify-content-center ">
    <div class="py-4 px-5 mt-5" style="border: 2px solid black;width: 50%;">
        <h2 class="mb-4">Login Page</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group mb-5">
                <label class="mb-2" for="username">Username : </label>
                <input type="text" class="form-control" id="username" placeholder="Username" name="username">
            </div>
            <div class="form-group mb-5">
                <label class="mb-2" for="password">Password</label>
                <input type="password" class="form-control" id="password" placeholder="Password" name="password">
            </div>
            {% if GOOGLE_CAPTCHA_SITE_KEY %}
            <script src='https://www.google.com/recaptcha/api.js'></script>
            <div class="g-recaptcha" data-sitekey="{{ GOOGLE_CAPTCHA_SITE_KEY }}"></div>
            <br>
            {% endif %}
            <input class="btn btn-lg btn-light mb-3" type="submit" value="Login">
        </form>
        {% if error %}
        <center>
            <h6 class="bg-danger px-5 py-2 rounded">
                {{ error }} {{ message }}
            </h6>
        <center>
        {% endif %}
        {% if messages %}
            {% for message in messages %}
            <h6 class="bg-danger px-5 py-2 rounded">
                {{ message }}
            </h6>
            {% endfor %}
        {% endif %}
    </div>
</div>

<script>
    var elm = '<a class="nav-link" href="#">Login</a>';
    $("#auth").append(elm);
</script>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #eee;">
  <span class="d-inline-block text-dark mx-5" tabindex="0" data-toggle="tooltip" title=" Powered By : mmtaee64@gmail.com" style="font-size: 22px;">
        Ocserv User Pannel
  </span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if user.is_authenticated %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'app:home' %}">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'app:add_user' %}">Add User</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'app:services' %}">Ocserv Services</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto mx-5">
      <li class="nav-item active" id="auth">
        <a class="nav-link" href="{% url 'app:change_password' %}">Change Password</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'app:logout' %}">Logout</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

app/templates/service.html
{% extends 'base.html' %}


{% block body %}
<h2 class="mt-4">Ocserv Service Page</h2>

<div class="d-flex justify-content-center">
    <div class="py-4 px-5 rounded text-center">
        <h6 class="text-capitalize">To chack Status and restart ocserv service you shoul type your password agin !!</h6>
        <button type="button" class="btn btn-outline-success my-2 mx-2" data-toggle="modal" data-target="#Modal"
            id="restartbtn">
            <i class="fa fa-play mx-1" aria-hidden="true"></i>
            Restart
        </button>

        <button type="button" class="btn btn-outline-success my-4 mx-2" data-toggle="modal" data-target="#Modal"
            id="statusbtn">
            <i class="fa fa-cogs mx-1" aria-hidden="true"></i>
            Status
        </button>

        <div class="bg-success px-4 py-3 col-9 mr-auto ml-auto text-capitalize rounded text-left" id="statusResult"
            style="border: 2px solid black;display: none;">
            <p>
                service : <span id="service"></span><br>
                status : <span id="status"></span><br>
                since : <span id="since"></span><br>
                uptime : <span id="uptime"></span><br>
            </p>
        </div>

        <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header border-bottom-0">
                        <button type="button" class="close">
                            <span>&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-title text-center text-dark mb-4">
                            <h4><span id="mode"></span> Ocserv Service</h4>
                        </div>
                        <div class="d-flex flex-column text-center mb-4">
                            <form id="form">
                                <div class="form-group mb-4">
                                    <input type="password" class="form-control" id="password"
                                        placeholder="Enter your password ...">
                                    <div class="bg-danger px-2 py-1 rounded text-center my-2"
                                        style="font-size: 12px;display: none;" id="errorForm">
                                        Invalid password
                                    </div>
                                </div>
                                <button type="button" class="btn btn-info btn-block btn-round" id="btnConfirm"
                                    disabled></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <script>
        function closeModal() {
            $("#errorForm").hide();
            $("#password").val("");
            $('#Modal').modal('hide');
        }
        $(".close").click(function () {
            closeModal()
        });

        $("#restartbtn").click(function () {
            let mode = "Restart";
            $("#mode").html(mode);
            $("#btnConfirm").html(mode);
            $('#Modal').modal('show');
        });

        $("#statusbtn").click(function () {
            let mode = "Status";
            $("#mode").html(mode);
            $("#btnConfirm").html(mode);
            $('#Modal').modal('show');
        });

        $("#password").keyup(function () {
            var inputPassword = $("#password").val()
            if (inputPassword.length > 0) {
                $("#btnConfirm").prop("disabled", false);
            } else {
                $("#btnConfirm").prop("disabled", true);
            }
        });

        $("#btnConfirm").click(function () {
            var mode = $("#btnConfirm").html().toLowerCase()
            var password = $("#password").val()
            var loading = '<i class="fa fa-spinner fa-spin mx-1"></i>Please wait...';
            var self = $("#restartConfirm");
            self.html(loading);
            self.prop("disabled", true);
            $.ajax({
                url: "/service_handler/",
                data: {
                    'mode': mode,
                    'password': password,
                    'service' : "ocserv",
                },
                success: function (response) {
                    for (let key in response) {
                        if (response[key] == "Deactive: (Not Running)"){
                            $("#statusResult").removeClass('bg-success')
                            $("#statusResult").addClass('bg-danger')
                        }
                        $("#" + key).html(response[key])
                    }
                    $("#statusResult").show();
                    $("#result").html(mode);
                    closeModal();
                },
                error: function (response) {
                    $("#errorForm").show();
                }
            });
        });

    </script>


    {% endblock %}